ACRA/acra

src/main/java/org/acra/ErrorReporter.java, src/main/java/org/acra/collector/CrashReportDataFactory.java
A rebase of https://github.com/ACRA/acra/pull/83
Addition of ReportBuilder etc.
=> Rebased changes for PR#83

pom.xml, src/main/java/org/acra/ACRAConfiguration.java, src/main/java/org/acra/ErrorReporter.java, src/main/java/org/acra/annotation/ReportsCrashes.java
=> Npe on end application

src/main/java/org/acra/util/DefaultHttpsSocketFactoryFactory.java, src/main/java/org/acra/util/TlsSniSocketFactory.java
Mergeable pull request for #171
=> Use custom SSLSocketFactory to enable Server Name Indication for HTTPS connections (contd.)

src/main/java/org/acra/CrashReportPersister.java, src/main/java/org/acra/collector/CollectorUtil.java, src/main/java/org/acra/collector/LogCatCollector.java, src/main/java/org/acra/util/JSONReportBuilder.java
I don't understand why JSONReportBuilder.java does not show the diff between two version but seems to be a full file change (I've used eclipse for all the files)
=> Fix all Reader close()

README.md, src/main/java/org/acra/ACRA.java, src/main/java/org/acra/BaseCrashReportDialog.java, src/main/java/org/acra/ErrorReporter.java
Fixes #178 
Notification is now created when the exception occurs.
Handles custom CrashReportDialog.
=> Fixes notification not opening Dialog

src/main/java/org/acra/ACRAConfiguration.java, src/main/java/org/acra/annotation/ReportsCrashes.java, src/main/java/org/acra/collector/CrashReportDataFactory.java
=> Allowing BuildConfig to be configurable.

src/main/java/org/acra/CrashReportDialog.java
=> User email wiped after dialog

src/main/java/org/acra/ACRA.java
=> Fixed typo

src/main/java/org/acra/ACRA.java, src/main/java/org/acra/ACRAConfiguration.java, src/main/java/org/acra/BaseCrashReportDialog.java, src/main/java/org/acra/CrashReportFinder.java, src/main/java/org/acra/ErrorReporter.java, src/main/java/org/acra/SendWorker.java, src/main/java/org/acra/collector/ConfigurationCollector.java, src/main/java/org/acra/collector/CrashReportDataFactory.java, src/main/java/org/acra/collector/DeviceFeaturesCollector.java, src/main/java/org/acra/collector/DisplayManagerCollector.java, src/main/java/org/acra/collector/DropBoxCollector.java, src/main/java/org/acra/collector/DumpSysCollector.java, src/main/java/org/acra/collector/LogCatCollector.java, src/main/java/org/acra/collector/SettingsCollector.java, src/main/java/org/acra/collector/SharedPreferencesCollector.java, src/main/java/org/acra/sender/HttpSender.java, src/main/java/org/acra/util/HttpRequest.java, src/main/java/org/acra/util/Installation.java, src/main/java/org/acra/util/JSONReportBuilder.java, src/main/java/org/acra/util/PackageManagerWrapper.java, src/main/java/org/acra/util/ReportUtils.java, src/main/java/org/acra/util/TlsSniSocketFactory.java, src/main/java/org/acra/util/ToastSender.java, src/test/java/org/acra/log/NonAndroidLog.java
=> fix mixed log usage

src/main/java/org/acra/ACRA.java, src/main/java/org/acra/log/HollowLog.java
add stub implementation of ACRALog, and helper
method to use it
=> allow disabling all logging

src/main/java/org/acra/collector/CrashReportDataFactory.java
Haven't been able to get tests to run, but tested it sending on Android device
Issue https://github.com/ACRA/acra/issues/274
=> https://github.com/ACRA/acra/issues/274

README.md, pom.xml, src/main/AndroidManifest.xml, src/main/java/org/acra/ErrorReporter.java, src/main/java/org/acra/collector/CrashReportDataFactory.java, src/main/java/org/acra/util/ReportUtils.java
=> Use AppCompat to handle removal of Notification methods in Android M (6.0)

src/main/java/org/acra/util/HttpRequest.java
=> Accept any HTTP response code >= 200 and < 300 as indication that the report was sent

build.gradle, proguard-rules.pro
=> Add build.gradle file to support the Android Studio when import project.

pom.xml, src/main/proguard/proguard.cfg
=> Adding proguard.cfg to published AAR

src/main/java/org/acra/ACRA.java, src/main/java/org/acra/ErrorReporter.java, src/main/java/org/acra/builder/ReportExecutor.java, src/main/java/org/acra/collector/CrashReportDataFactory.java, src/main/java/org/acra/collector/DropBoxCollector.java, src/main/java/org/acra/collector/LogCatCollector.java, src/main/java/org/acra/collector/SettingsCollector.java, src/main/java/org/acra/collector/SharedPreferencesCollector.java, src/main/java/org/acra/config/ACRAConfig.java, src/main/java/org/acra/config/ACRAConfiguration.java, src/main/java/org/acra/dialog/BaseCrashReportDialog.java, src/main/java/org/acra/dialog/CrashReportDialog.java, src/main/java/org/acra/prefs/SharedPreferencesFactory.java, src/main/java/org/acra/sender/DefaultReportSenderFactory.java, src/main/java/org/acra/sender/EmailIntentSender.java, src/main/java/org/acra/sender/EmailIntentSenderFactory.java, src/main/java/org/acra/sender/HttpSender.java, src/main/java/org/acra/sender/HttpSenderFactory.java, src/main/java/org/acra/sender/ReportDistributor.java, src/main/java/org/acra/sender/ReportSenderFactory.java, src/main/java/org/acra/sender/SenderService.java, src/main/java/org/acra/sender/SenderServiceStarter.java, src/main/java/org/acra/util/ApplicationStartupProcessor.java, src/main/java/org/acra/util/HttpRequest.java
=> Issue 354 Removing ACRAConfiguration's dependency on ReportCrashes.

src/main/java/org/acra/collector/CrashReportDataFactory.java
These are generally the same location but don't need to be.
=> Looking for BuildConfig class in the package defined in AndroidManifet, not the package of the Application class.

README.md, src/main/java/org/acra/config/ACRAConfiguration.java, src/main/java/org/acra/config/ConfigurationBuilder.java
=> Issue-365 NPE on ConfigurationBuilder.build because there was no annotation on Application

src/main/java/org/acra/file/ReportLocator.java
=> Issue-369 Need to return an empty array of unapproved files.

pom.xml
Due to http://stackoverflow.com/questions/35618098/android-support-libraries-23-2-0-cause-app-to-crash
=> Updating the Android support libraries to 2.3.2.1 

src/main/java/org/acra/security/AssetKeyStoreFactory.java, src/main/java/org/acra/security/BaseKeyStoreFactory.java, src/main/java/org/acra/security/FileKeyStoreFactory.java, src/main/java/org/acra/security/KeyStoreFactory.java, src/main/java/org/acra/security/ResourceKeyStoreFactory.java
perform https://github.com/ACRA/acra/pull/388#issuecomment-203620424
=> add license notes

src/main/java/org/acra/ACRA.java
Change according to https://github.com/ACRA/acra/issues/424#issuecomment-208080653
=> `android.os.Process.myPid()` call removed in favor of `/proc/self`

build.gradle, pom.xml, src/main/AndroidManifest.xml
This loads as much as possible from the pom.xml into the build.gradle, so things don't have to be changed in two places.
=> Slave gradle to maven

src/main/java/org/acra/collector/SettingsCollector.java
I think I just missed this one when I initially cleaned up the reflection calls.
=> Simplify collectGlobalSettings

src/main/java/org/acra/util/HttpRequest.java
for define client ACRA version in php use variable $_SERVER['HTTP_USER_AGENT']
=> add ACRA version in field User-Agent

src/main/java/org/acra/config/ACRAConfigurationException.java, src/main/java/org/acra/config/ConfigurationBuilder.java
Fail-fast in case of bad class configuration.
=> Check if configured classes can be instantiated

src/main/java/org/acra/dialog/BaseCrashReportDialog.java
=> Make BaseCrashReportDialog extend FragmentActivity to increase its versatility

src/main/java/org/acra/file/LastModifiedComparator.java
=> Change LastModifiedComparator implementation to be identical with Long.compare()

src/main/java/org/acra/util/HttpRequest.java
=> Repeat request only on 408 or 500+ response

src/main/java/org/acra/collections/ImmutableSet.java
=> fixed set iteration order

src/main/java/org/acra/config/ConfigurationBuilder.java
Fix #525 (now for real).
Related: #526
=> Fixed iteration order mixed

src/main/java/org/acra/ErrorReporter.java, src/main/java/org/acra/annotation/ReportsCrashes.java, src/main/java/org/acra/builder/ReportExecutor.java, src/main/java/org/acra/config/ACRAConfiguration.java, src/main/java/org/acra/config/ConfigurationBuilder.java, src/main/java/org/acra/util/ProcessFinisher.java
I chose to export that functionality into a separate class, as ReportExecutor has already too many different tasks imo.
Solution for #477 .
=> Add stopServicesOnCrash

src/main/java/org/acra/sender/HttpSender.java, src/main/java/org/acra/sender/HttpSenderFactory.java
Allows easier extension of HttpSender
=> Improve HttpSender reusability

acra/src/main/AndroidManifest.xml, acra/src/main/java/org/acra/annotation/ReportsCrashes.java, acra/src/main/java/org/acra/attachment/AcraContentProvider.java, acra/src/main/java/org/acra/sender/EmailIntentSender.java
Based on #565 
@MFlisar I think you requested this.
=> Send report as attachment instead of body

acra/src/main/java/org/acra/annotation/NoPropagation.java, acra/src/main/java/org/acra/config/ConfigurationBuilder.java, annotationprocessor/src/main/java/org/acra/ModelUtils.java
=> Rename @hide to fix conflict with androids internal @hide annotation

acra/src/main/java/org/acra/builder/ReportExecutor.java
=> fix thread released too early when using toast

acra-core/src/main/java/org/acra/sender/SenderService.java
=> Fix SenderService not showing toast

acra-core/src/main/java/org/acra/data/StringFormat.java
=> prevent urlencode nullpointer

acra-core/src/main/java/org/acra/builder/ReportExecutor.java, acra-core/src/main/java/org/acra/collector/BaseReportFieldCollector.java, acra-core/src/main/java/org/acra/collector/Collector.java, acra-core/src/main/java/org/acra/collector/LogCatCollector.java, acra-core/src/main/java/org/acra/config/BaseCoreConfigurationBuilder.java, acra-core/src/main/java/org/acra/config/ReportingAdministrator.java, acra-core/src/main/java/org/acra/data/CrashReportData.java, acra-core/src/main/java/org/acra/data/CrashReportDataFactory.java, acra-core/src/main/java/org/acra/interaction/ReportInteraction.java, acra-core/src/main/java/org/acra/interaction/ReportInteractionExecutor.java, acra-core/src/main/java/org/acra/legacy/ReportMigrator.java, acra-core/src/main/java/org/acra/sender/DefaultReportSenderFactory.java, acra-core/src/main/java/org/acra/sender/ReportSenderFactory.java, acra-core/src/main/java/org/acra/sender/SenderService.java, acra-core/src/main/java/org/acra/util/ApplicationStartupProcessor.java, acra-core/src/main/java/org/acra/util/ProcessFinisher.java, acra-core/src/main/java/org/acra/util/StreamReader.java, acra-core/src/main/java/org/acra/util/StubCreator.java, acra-javacore/src/main/java/org/acra/ReportField.java, acra-limiter/src/main/java/org/acra/config/LimitingReportAdministrator.java, acra-toast/src/main/java/org/acra/interaction/ToastInteraction.java, annotationprocessor/build.gradle, annotationprocessor/src/main/java/org/acra/processor/AcraAnnotationProcessor.java, annotationprocessor/src/main/java/org/acra/processor/element/ConfigElement.java, annotationprocessor/src/main/java/org/acra/processor/util/InitializerVisitor.java, annotationprocessor/src/main/java/org/acra/processor/util/Types.java, gradle.properties
=> ReportingAdministrator improvements

acra-core/src/main/AndroidManifest.xml, acra-core/src/main/java/org/acra/util/ApplicationStartupProcessor.java
=> Fix issues with JobIntentService on pre-oreo devices

acra-core/src/main/java/org/acra/builder/ReportExecutor.java, acra-core/src/main/java/org/acra/config/BaseCoreConfigurationBuilder.java, acra-core/src/main/java/org/acra/data/CrashReportDataFactory.java, acra-core/src/main/java/org/acra/interaction/ReportInteractionExecutor.java, acra-core/src/main/java/org/acra/sender/DefaultReportSenderFactory.java
=> Use fixed classloader for serviceloader

acra-core/src/main/java/org/acra/builder/ReportExecutor.java, acra-core/src/main/java/org/acra/file/CrashReportFileNameParser.java, acra-core/src/main/java/org/acra/sender/SenderService.java, acra-core/src/main/java/org/acra/util/ApplicationStartupProcessor.java
=> Fix handleSilentException bugs

acra-core/src/main/AndroidManifest.xml
=> Remove maxsdkversion for wake lock

acra-advanced-scheduler/build.gradle, acra-core/build.gradle, acra-dialog/build.gradle, acra-notification/build.gradle, build.gradle
Workaround for gradle/gradle#3170
Closes #700
=> Fix pom dependencies not including aar type

acra-limiter/src/main/java/org/acra/config/LimiterData.java
=> Call indexof on correct string in limiter

acra-mail/src/main/java/org/acra/annotation/AcraMailSender.java, acra-mail/src/main/java/org/acra/sender/EmailIntentSender.java
=> Add option for mail body

acra-core/src/main/java/org/acra/builder/LastActivityManager.java, acra-core/src/main/java/org/acra/util/ProcessFinisher.java, acra-javacore/src/main/java/org/acra/collections/WeakStack.java
Fixes issue described in https://stackoverflow.com/questions/54430507/how-to-get-acra-to-stop-app-when-exception-is-not-in-main-activity
=> Finish all activities in stack instead of only last one

acra-core/src/main/java/org/acra/sender/JobSenderService.java, acra-core/src/main/java/org/acra/sender/LegacySenderService.java
=> Fix networkonmaintread

acra-core/proguard.cfg
=> Fix Proguard Plugin Rule

acra-advanced-scheduler/src/main/java/org/acra/scheduler/AdvancedSenderScheduler.java, acra-core/src/main/java/org/acra/scheduler/DefaultSenderScheduler.java
=> Prevent exception for no constraints with overrideDeadline

acra-toast/src/main/java/org/acra/interaction/ToastInteraction.java
=> ToastInteraction fixes

acra-mail/src/main/java/org/acra/sender/EmailIntentSender.java
=> Help gmail find our crash reports in intents without attachments

acra-mail/src/main/java/org/acra/sender/EmailIntentSender.kt
=> Fix Gmail report sending on Android Q+

acra-core/src/main/java/org/acra/data/CrashReportDataFactory.kt, gradle/libs.versions.toml
=> Keep collector order even in parallel run

acra-core/src/main/java/org/acra/collector/DeviceIdCollector.kt, acra-javacore/src/main/java/org/acra/ReportField.kt
=> Add version check for getDeviceId

web/docs/Custom-Extensions.mdx
This PR updated `Custom-Extensions` section. Added KSP documentation. Updated `auto-service` version
close #1230
=> Updated Custom-Extensions section. Added KSP documentation. 
