- src/main/java/org/acra/ACRA.java
- src/main/java/org/acra/ACRAConfiguration.java
- src/main/java/org/acra/ACRAConstants.java
- src/main/java/org/acra/ErrorReporter.java
- src/main/java/org/acra/ExceptionHandlerInitializer.java
- src/main/java/org/acra/ReportField.java
- src/main/java/org/acra/annotation/ReportsCrashes.java
- src/main/java/org/acra/collector/CrashReportDataFactory.java
- src/main/java/org/acra/collector/MediaCodecListCollector.java
- src/main/java/org/acra/collector/ThreadCollector.java
- src/main/java/org/acra/jraf/android/util/activitylifecyclecallbackscompat/ApplicationHelper.java
- src/main/java/org/acra/sender/HttpSender.java
- src/main/java/org/acra/sender/ReportSender.java
Java 8 enables some strict rule checking with doclint that breaks maven compilation when it raises errors. This commit fixes those errors, as well as warnings raised for missing javadoc tags.
> Fix javadoc issues preventing compilation with Java 8

- src/main/java/org/acra/ACRA.java
- src/main/java/org/acra/ACRAConfiguration.java
Calling setMode on ACRAConfiguration calls checkCrashResources on ACRA. However this does not provide a config parameter, which means that it checks against the current ACRA config. This will not really work when creating a config object for the annotation less configuration.
> Add config parameter to checkCrashResources

- src/main/java/org/acra/ErrorReporter.java
Previously, `Uncaught exception\n` was not prepended to the
stacktrace and existing receivers may not be expecting it.
This change was introduced by #210 (nee #83).
If clients want to include a message before the stack trace,
they may still do so, but it should not be forced there
unconditionally.
> Remove backwards incompatible change introduced by #210

- src/main/java/org/acra/ErrorReporter.java
Three small commits here to optimized/cleanup `checkReportsOnApplicationStart` a bit:
1. There was an extraneous call to getCrashReportFiles which I've removed.
1. There was a variable to capture `ACRA.getConfig().mode()` but it wasn't used consistently.
1. I inverted the logic for deleting old reports on startup so that folks who don't care about this (`ACRA.getConfig().deleteOldUnsentReportsOnApplicationStart() == false`) don't have to pay the slight startup penalty of the check.
> Optimize/cleanup checkReportsOnApplicationStart

- src/main/java/org/acra/ACRAConfiguration.java
- src/main/java/org/acra/BaseCrashReportDialog.java
- src/main/java/org/acra/CrashReportDialog.java
- src/main/java/org/acra/ErrorReporter.java
- src/main/java/org/acra/annotation/ReportsCrashes.java
Continuing on from #218, I've created a new base class for `CrashReportDialog` which implements the minimum functionality for sending a crash report, and allowed setting of an arbitrary Activity for the CrashReportActivity
> Add ability to have custom CrashReportDialog v2

- src/main/java/org/acra/collector/CrashReportDataFactory.java
`context.getPackageName() + ".BuildConfig";` will not work if using applicationIdSuffix or applicationId is different than the application source package name. 
Example:
- you have `org.acra.sample` as package name in your source code,
- you have 2 flavors _free_ and _pro_ with applicationId `org.acra.sample.free` and `org.acra.sample.pro` respectively,
When you build the _free_ flavor the `context.getPackageName()` will return `org.acra.sample.free` but BuildConfig will be based on your source code package name not the applicationId therefore will be located at `org.acra.sample.BuildConfig`. 
Since ACRA is initialized in the Application class we can get the name of the source code package name to get the location of BuildConfig.
> Do not use getPackageName() when looking for BuildConfig class

- src/main/java/org/acra/collector/CrashReportDataFactory.java
Fixes one of 2 issues raised in #236
> Fix check for whether to gather read logs. Has permission if either READ_LOGS_PERMISSION or API >= 16.

- src/main/java/org/acra/ErrorReporter.java
- src/main/java/org/acra/collector/ConfigurationCollector.java
- src/main/java/org/acra/collector/CrashReportDataFactory.java
Using reflection to collect the initial device configuration is
fairly expensive and impacts application startup time, especially
on older devices. Profiling on a Moto G showed the
ConfigurationCollector taking 70% of the ACRA.init() CPU time.
> Only collect initial configuration if we're going to report it

- src/main/java/org/acra/collector/ReflectionCollector.java
newer Build fields are string arrays
> reflectioncollector: better values for arrays

- pom.xml
- src/main/java/org/acra/CrashReportDialog.java
- src/main/java/org/acra/ErrorReporter.java
- src/main/java/org/acra/collector/Compatibility.java
- src/main/java/org/acra/collector/CrashReportDataFactory.java
- src/main/java/org/acra/collector/DeviceFeaturesCollector.java
- src/main/java/org/acra/collector/DisplayManagerCollector.java
- src/main/java/org/acra/collector/LogCatCollector.java
- src/main/java/org/acra/collector/SettingsCollector.java
- src/main/java/org/acra/jraf/android/util/activitylifecyclecallbackscompat/ActivityLifecycleCallbacksWrapper.java
- src/main/java/org/acra/jraf/android/util/activitylifecyclecallbackscompat/ApplicationHelper.java
- src/main/java/org/acra/util/TlsSniSocketFactory.java
Replaced String#isEmpty with TextUtils#isEmpty.
Removed/replaced other instances that would have stopped ACRA working with APIs between 3 and 9.
> ACRA now supports back to API 3 once again.

- src/main/java/org/acra/collector/LogFileCollector.java
> Handling poorly configured application log file.

- src/main/java/org/acra/SendWorker.java
> Ensuring that if multiple senders and the first Sender fails that the others are attempted

- src/main/java/org/acra/util/HttpRequest.java
> Always initialize TrustManager, even if KeyStore is null (thats ok).

- pom.xml
- src/main/java/org/acra/ErrorReporter.java
- src/main/java/org/acra/util/HttpRequest.java
Replaced Authenticator with Authorization Request property as pre Gingerbread versions of UrlConnection don't respect Authenticator.
Fix for #311
> Allowing authentication with crash server in pre Gingerbread apps.

- src/main/java/org/acra/util/HttpRequest.java
We already have the full request in memory, so no loss there.
And providing the length supports servers that can't handle chunked mode.
Fixes #310
> Configuring request length instead of using chunked streaming mode.

- README.md
- build.gradle
- pom.xml
- src/main/AndroidManifest.xml
- src/main/java/org/acra/ACRA.java
- src/main/java/org/acra/ErrorReporter.java
- src/main/java/org/acra/util/HttpRequest.java
Removing use of inet.harder library.
ACRA requires Froyo or greater. If no Froyo then ACRA disables itself.
> Remove inet harder

- src/main/java/org/acra/collector/CrashReportDataFactory.java
Moved logcat collection to a much earlier point in crash data collection so it is not polluted by messages generated by data collection. Some ROMs leave verbose messages on for Settings, that generates 2 lines per variable read and overwrites the whole 100 lines default logcat buffer. Example on an Acer S57 on 4.4.4:
```
12-16 00:33:21.564 V/Provider/Settings(29238): get setting for user 0 by user 0 so skipping cache
12-16 00:33:21.564 V/Provider/Settings(29238): from db cache, name = wifi_display_qe_on , value = 1
12-16 00:33:21.564 V/Provider/Settings(29238): get setting for user 0 by user 0 so skipping cache
12-16 00:33:21.565 V/Provider/Settings(29238): from db cache, name = wifi_display_max_resolution , value = 0
12-16 00:33:21.565 V/Provider/Settings(29238): get setting for user 0 …
```
> Move logcat collection to prevent pollution during crash data gathering

- src/main/java/org/acra/collector/LogFileCollector.java
context.openFileInput() name parameter can not contain path separators. So when a relative log file path is passed to ACRA config, we have to build full path to the file, then open it with FileInputStream().
> Fix LogFileCollector to work with getFilesDir() sub-directories

- src/main/java/org/acra/util/HttpRequest.java
As DEFAULT follows RFC 2045 which wraps every 76 chars (and at end of String).
This fixes #338 which was all about basic authentication, especially for long credentials.
> Base64 authorization String needs to be NO-WRAP

- build.gradle
- src/main/java/org/acra/CrashReportDialog.java
I liked the default dialog, but I wanted to apply minimal changes to it. That is currently very hard. In my implementation (note: no logic changed) I have several Methods which can be overridden to modify just parts of the dialog:
- addViewToDialog can be used to add view to the start (call before buildCutomView) or end of the dialog (call after buildCustomView)
- getMainView, getCommentPrompt and getEmailPrompt allow to modify or replace specific parts of the dialog
- buildAndShowDialog can be used to e.g. prevent the creation of the dialog in certain situations
- getDialog for more modifications to the dialog (e.g third button)
These allow more modifications than I would need, but I thought it will help in the future if it is more flexible.
> Make Dialog easier to extend

- src/main/java/org/acra/ErrorReporter.java
We should only log the error once.
> Remove second report of stacktrace.

- src/main/java/org/acra/ACRA.java
- src/main/java/org/acra/ErrorReporter.java
- src/main/java/org/acra/builder/LastActivityManager.java
- src/main/java/org/acra/builder/ReportExecutor.java
- src/main/java/org/acra/collector/CrashReportDataFactory.java
- src/main/java/org/acra/collector/DropBoxCollector.java
- src/main/java/org/acra/collector/LogCatCollector.java
- src/main/java/org/acra/collector/SharedPreferencesCollector.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/dialog/BaseCrashReportDialog.java
- src/main/java/org/acra/file/BulkReportDeleter.java
- src/main/java/org/acra/legacy/ReportMigrator.java
- src/main/java/org/acra/sender/DefaultReportSenderFactory.java
- src/main/java/org/acra/sender/HttpSender.java
- src/main/java/org/acra/sender/ReportDistributor.java
- src/main/java/org/acra/sender/SenderService.java
- src/main/java/org/acra/sender/SenderServiceStarter.java
- src/main/java/org/acra/util/HttpRequest.java
- src/main/java/org/acra/util/JSONReportBuilder.java
- src/main/java/org/acra/util/PackageManagerWrapper.java
- src/main/java/org/acra/util/ToastSender.java
All debug messages are prefix by `if (ACRA.DEV_LOGGING)`, so if you want ACRA debug configure `ACRA.DEV_LOGGING` on first.
> Hide all ACRA debug log unless ACRA.DEV_LOGGING is switched on.

- src/main/java/org/acra/ACRA.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ACRAConfigurationFactory.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
Replaced ACRAConfigurationFactory with ConfigurationBuilder.
Deprecated all set methods on ACRAConfiguration.
> Moving towards making ACRAConfiguration immutable.

- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
- src/main/java/org/acra/security/AssetKeyStoreFactory.java
- src/main/java/org/acra/security/BaseKeyStoreFactory.java
- src/main/java/org/acra/security/FileKeyStoreFactory.java
- src/main/java/org/acra/security/KeyStoreFactory.java
- src/main/java/org/acra/security/ResourceKeyStoreFactory.java
- src/main/java/org/acra/sender/HttpSender.java
- src/main/java/org/acra/util/HttpRequest.java
Fix #387 by passing a factory instead of the keystore itself.
> Instead of KeyStore pass a KeyStoreFactory around.

- src/main/java/org/acra/collector/DropBoxCollector.java
replacing deprecated api with recommended equivalent.
It is most certainly a good idea to get rid of deprecated api, as it may otherwise get to be a problem in the future.
I have started to split up my big pull request (I will remove it as soon as I'm done), so it can be discussed and approved/rejected part by part. This is the fifth part.
> Replaced time with calendar & dateformat

- src/main/java/org/acra/dialog/BaseCrashReportDialog.java
- src/main/java/org/acra/dialog/CrashReportDialog.java
This is a follow-up to #341. 
I have misplaced some code while reworking the dialog last time (which results in unexpected behaviour of classes overiding certain methods without calling super), I think that should now be better.
Also the base now provides the data from the intent to subclasses, so they don't have to deserialize it again.
I consider this a cosmetic update: Nice to have, but not that important.
I have started to split up my big pull request (I will remove it as soon as I'm done), so it can be discussed and approved/rejected part by part. This is the seventh and so far last part.
> Improve Dialogs

- src/main/java/org/acra/ACRAConstants.java
- src/main/java/org/acra/annotation/ReportsCrashes.java
- src/main/java/org/acra/builder/ReportExecutor.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
This was required in the past when a shutdown might stop the crash report from being sent.
Now that we are using the ReportSender from another process this is no longer the case.
Solution for #382
> Removing ability to configure reports to NOT send at shutdown.

- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
- src/main/java/org/acra/util/HttpRequest.java
Fix #402 .
Also:
Add @Nullabale for keyStoreFactory to prevent this in the future.
Make setter in ConfigurationBuilder return itself for chained calls where missing (e.g. on setKeyStoreFactory).
> Fix TrustManagerFactory not initialized when no KeyStoreFactory provided

- src/main/java/org/acra/ACRA.java
Allow apps to easily avoid starting services in `Application.onCreate` when the SenderService has caused the :acra process to be started.
> Exposing ACRA.isACRASenderServiceProcess()

- build.gradle
- src/main/java/org/acra/dialog/BaseCrashReportDialog.java
- src/main/java/org/acra/dialog/CrashReportDialog.java
> BaseCrashReportDialog

- src/main/java/org/acra/collector/CollectorUtil.java
- src/main/java/org/acra/collector/DumpSysCollector.java
- src/main/java/org/acra/collector/LogCatCollector.java
- src/main/java/org/acra/collector/LogFileCollector.java
- src/main/java/org/acra/file/CrashReportPersister.java
- src/main/java/org/acra/util/IOUtils.java
- src/main/java/org/acra/util/JSONReportBuilder.java
I noticed a lot of duplicated code regarding read of input strings in the collectors, so I extraced it into a method in `CollectorUtil`.
(Also added license in that file)
> Extract read of streams into strings

- src/main/java/org/acra/ACRA.java
perform https://github.com/ACRA/acra/issues/424#issuecomment-207685808
adapted from http://stackoverflow.com/a/21389402/4388512
Also: made DEV_LOGGING non-final. Developers might want to change this wihle testing their app. (It was made final by me in the first place in one of the automated passes.)
Depends upon #426
> New implementation for getCurrentProcessName

- src/main/java/org/acra/ACRA.java
- src/main/java/org/acra/ErrorReporter.java
- src/main/java/org/acra/collector/DisplayManagerCollector.java
- src/main/java/org/acra/collector/MediaCodecListCollector.java
- src/main/java/org/acra/collector/ThreadCollector.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
- src/main/java/org/acra/dialog/BaseCrashReportDialog.java
- src/main/java/org/acra/dialog/CrashReportDialog.java
- src/main/java/org/acra/file/LastModifiedComparator.java
- src/main/java/org/acra/log/HollowLog.java
- src/main/java/org/acra/security/AssetKeyStoreFactory.java
- src/main/java/org/acra/security/BaseKeyStoreFactory.java
- src/main/java/org/acra/security/FileKeyStoreFactory.java
- src/main/java/org/acra/security/ResourceKeyStoreFactory.java
Hide some classes which don't need to be public.
Supress Warnings for classes and methods intended for usage in the final application (not the library itself).
> Adjust visibility, suppress warnings for classes intended for users

- build.gradle
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
Add convenience method to ConfigurationBuilder: It allows to set only some ReportFields, but use the default configuration for everything else.
Example from one of my projects:
```
ArrayList<ReportField> fields = new ArrayList<>(Arrays.asList(ACRAConstants.DEFAULT_REPORT_FIELDS));
fields.add(ReportField.APPLICATION_LOG);
ConfigurationBuilder builder = new ConfigurationBuilder(this)
.setApplicationLogFile(Logger.getPath())
.setCustomReportContent(fields.toArray(new ReportField[fields.size()]));
```
would be with this just: 
```
ConfigurationBuilder builder = new ConfigurationBuilder(this)
.setApplicationLogFile(Logger.getPath())
.setReportField(ReportField.APPLICATION_LOG, true);
```
I also fixed the javadoc in ConfigurationBuilder. It still said "@return The updated ACRA configuration" …
> Configurationbuilder

- src/main/java/org/acra/config/ConfigurationBuilder.java
Remove a throws declaration for an Exception that is never thrown. (I guess this is a copy-paste issue from ACRAConfiguration).
If this should be checked in `ConfigurationBuilder` at all, it should be in the `build()` method.
> Configurationbuilder should not throw Exception

- src/main/java/org/acra/annotation/ReportsCrashes.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
- src/main/java/org/acra/dialog/CrashReportDialog.java
The default theme (Theme.Dialog) is not anymore up-to-date. Giving an easy option to change this and make the dialog look better and more fitting seems reasonable.
> Add configuration for dialog theme

- src/main/java/org/acra/ACRAConstants.java
- src/main/java/org/acra/annotation/ReportsCrashes.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
- src/main/java/org/acra/security/AssetKeyStoreFactory.java
- src/main/java/org/acra/security/BaseKeyStoreFactory.java
- src/main/java/org/acra/security/FileKeyStoreFactory.java
- src/main/java/org/acra/security/KeyStoreFactory.java
- src/main/java/org/acra/security/KeyStoreHelper.java
- src/main/java/org/acra/security/NoKeyStoreFactory.java
- src/main/java/org/acra/util/HttpRequest.java
It seems to be problematic to expect every user to honor that keystorefactories have to be serializable. 
Also the keystorefactory could not be configured with the annotation.
This is why I rewrote it to pass the keystorefactory class (which doesn't have to be serializable) instead of the object to the configuration. This also decreases the size of the configuration object itself.
I also added configuration options for the 3 default certificate locations: raw resources, assets and files. (Because passing the KeyStoreFactory implementations wont work, they have no empty constructor.)
> Keystorefactory: Pass class instead of object

- src/main/java/org/acra/collector/CrashReportDataFactory.java
- src/main/java/org/acra/collector/DropBoxCollector.java
- src/main/java/org/acra/collector/LogCatCollector.java
- src/main/java/org/acra/collector/SharedPreferencesCollector.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/security/KeyStoreHelper.java
- src/main/java/org/acra/security/NoKeyStoreFactory.java
- src/main/java/org/acra/sender/SenderServiceStarter.java
- src/main/java/org/acra/util/ImmutableList.java
- src/main/java/org/acra/util/ImmutableMap.java
- src/main/java/org/acra/util/ImmutableSet.java
- src/main/java/org/acra/util/UnmodifiableIteratorWrapper.java
- src/main/java/org/acra/util/UnmodifiableListIteratorWrapper.java
perform https://github.com/ACRA/acra/issues/421#issuecomment-212401471
`ACRAConfiguration` now only contains the logic of `checkCrashResources`. Maybe this could move somewhere else, so that it is only a configuration object and nothing else?
> Make ACRAConfiguration final

- src/main/java/org/acra/ACRAConstants.java
- src/main/java/org/acra/annotation/ReportsCrashes.java
- src/main/java/org/acra/builder/ReportExecutor.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
Perform as noted in https://github.com/ACRA/acra/issues/421#issuecomment-210173083
> Restructure forceCloseDialogAfterToast to alsoReportToAndroidFramework

- src/main/java/org/acra/sender/EmailIntentSender.java
- src/main/java/org/acra/sender/HttpSender.java
I don't know how this could slip through, but ACRA didn't compile at all, because of one of the removed methods of ACRAConfiguration being used.
> Fix: removed method used

- src/main/java/org/acra/config/ConfigurationBuilder.java
If no annotation is set and no mode is set, the switch lead to a NullPointer.
> Fix potential NullPointer in ConfigurationBuilder.build

- src/main/java/org/acra/dialog/BaseCrashReportDialog.java
ErrorReporter allows null exceptions, so the dialog should too.
> Allow null exception in dialog

- src/main/java/org/acra/config/ConfigurationBuilder.java
This could lead to a crash if no annotation is present and the values are not configured manually.
> Correct defaults in configurationbuilder

- src/main/java/org/acra/collections/ImmutableList.java
- src/main/java/org/acra/collector/LogCatCollector.java
- src/main/java/org/acra/config/ACRAConfiguration.java
Because ordering might be mixed up otherwise.
I was not aware that logcatArguments is ordering-sensitive until I saw a stacktrace in one of my configurations. With a set logcat collection will crash randomly because the set mixed the arguments.
> Use list instead of set for logcatArguments

- src/main/java/org/acra/config/ConfigurationBuilder.java
This is somewhat critical, because I'd expect that most users use the default report fields. These Reports will then include no fields at all, which renders the reports pretty useless.
> Fix annotation default mistaken as custom value

- src/main/java/org/acra/collector/CrashReportDataFactory.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
While writing some tests I noticed that BuildConfig class is the only value which differs in the not-configured-value between the ConfigurationBuilder and the annotation. There is no real reason to keep it that way.
> Never return null for BuildConfig class

- README.md
- Removed the Google+ links, as news aren't posted there anymore.
- Fixed link to backends.
- Updated info for Acralyzer
> Readme: Remove Google+, fix links

- src/main/java/org/acra/util/HttpRequest.java
My Acralyzer instance was spammed with requests (and now shut down by the host) due to one client retrying to connect in case of a 401 UNAUTHORIZED response.
I do not know how it could happen that just one client sends bad login credentials, but retrying is not the correct way to handle this.
Similarily a 405 response means the server doesn't accept get/post. Retrying with the same method won't do anything.
> Discard request in case of 401 or 405

- src/main/AndroidManifest.xml
- src/main/java/org/acra/builder/LastActivityManager.java
- src/main/java/org/acra/builder/ReportExecutor.java
> Call finish on UI thread

- src/main/java/org/acra/annotation/ReportsCrashes.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
- src/main/java/org/acra/config/DefaultRetryPolicy.java
- src/main/java/org/acra/config/RetryPolicy.java
- src/main/java/org/acra/sender/ReportDistributor.java
I saw this post https://groups.google.com/forum/#!topic/acra-discuss/hFf5jpNR188 and I think there is no option to configure this yet. So I added this.
> Add RetryPolicy configuration

- src/main/java/org/acra/annotation/ReportsCrashes.java
- src/main/java/org/acra/collector/CrashReportDataFactory.java
- src/main/java/org/acra/collector/LogFileCollector.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
- src/main/java/org/acra/file/Directory.java
Android paths are becoming more and more relative. This provides a way to specify a relative log file path not only in the files directory.
This is fully backwards compatible (as the default FILES_LEGACY behaves as the old code).
> ApplicationLogFileDir

- src/main/java/org/acra/config/ConfigurationBuilder.java
- src/main/java/org/acra/sender/SenderService.java
- src/main/java/org/acra/sender/SenderServiceStarter.java
Fix #500 and some strongly related changes
> Handle null Intent on SenderService restart

- src/main/java/org/acra/collector/LogCatCollector.java
Current implementation ignores the limit, as there are two lists in use (one in the collector, one in IOUtils), and the limit is set on the wrong one. This fixes that problem.
Additionally I simplified the usage of myPidStr by declaring it final.
> Simplify logcatcollector

- src/main/java/org/acra/builder/ReportExecutor.java
I finally found out what causes #478. The ActivityManagerService kills all processes of a package when a debugger is detached from one of them due to a crash.
The best solution I could come up with was to not kill the process in this situation.
However, this might have unknown side-effects, which is why it displays (and logs) a warning about it.
> Fix: Debugger

- src/main/java/org/acra/dialog/BaseCrashReportDialog.java
> Add a preInit() method to BaseCrashReportDialog for e.g. AppCompatDelegate setup

- pom.xml
- src/main/java/org/acra/collector/DisplayManagerCollector.java
- src/main/java/org/acra/collector/LogCatCollector.java
- src/main/java/org/acra/collector/LogFileCollector.java
- src/main/java/org/acra/dialog/CrashReportDialog.java
Note: Support library version update was required for ContextCompat.getNoBackupFilesDir.
Note2: The removed condition was always false, as the minimum supported version is FROYO.
Note3: I did not use the newest support library version (24.2.0), because it has minSdk 9. At some point we should follow that, but right now it is not necessary (altough we could reduce the aar size with it, as 24.2.0 is modularized. see https://developer.android.com/topic/libraries/support-library/revisions.html).
> Use compat classes where appropriate, use PrefUtils instead of commit

- src/main/java/org/acra/ACRAConstants.java
- src/main/java/org/acra/annotation/ReportsCrashes.java
- src/main/java/org/acra/collector/LogCatCollector.java
- src/main/java/org/acra/config/ACRAConfiguration.java
- src/main/java/org/acra/config/ConfigurationBuilder.java
- src/main/java/org/acra/util/IOUtils.java
- src/main/java/org/acra/util/NonBlockingBufferedReader.java
- src/main/java/org/acra/util/NonblockingBufferedReader.java
I encounter and issue with handleSilentException and ReportField.LOGCAT on Lenovo TAB 2 A8-50F.
It appears that when an ProgressDialog is shown a lot of useless info are spitted to the logs and ACRA spends couple of minutes to receive logs and send report due the fact that reading from InputStream is done in a blocking way.
I think is better to have at least an empty log info than a lots of useless logs due the fact that Stream is blocked for writing.
Also for my particular context handling ACRA's sending exception in another thread helped me, and received some info due the fact ProgressDialog is closed immediately after.
`    	new Thread(new Runnable() {
@Override
public void run() {
ACRA.getErrorReporter().handleSilentException(e);
}
}).start();` …
> read logcat logs in nonblocking mode with end timeout

- src/main/java/org/acra/config/ConfigurationBuilder.java
BuildConfig class does not have to be instantiatable and thus should not be checked for that.
Resolves a rare issue where proguard made the constructor of that class private.
> Remove BuildConfig from validated classes

- pom.xml
- src/main/res/values/strings.xml
Added bogus resource entry to force android-maven-plugin to create res folder and R.txt in AAR to conform to AAR file structure. Fix for #538
> Add res folder and R.txt to AAR

- src/main/java/org/acra/legacy/ReportConverter.java
- src/main/java/org/acra/sender/HttpSender.java
- src/main/java/org/acra/sender/HttpSenderFactory.java
> Fix nullpointer in HttpSender & Exception in ReportConverter

- acra/src/main/AndroidManifest.xml
- acra/src/main/java/org/acra/annotation/ReportsCrashes.java
- acra/src/main/java/org/acra/attachment/AcraContentProvider.java
- acra/src/main/java/org/acra/file/Directory.java
- acra/src/main/java/org/acra/sender/EmailIntentSender.java
> File attachment support (fix)

- acra/src/main/java/org/acra/util/PackageManagerWrapper.java
> swallow errors in addition to exceptions if packagemanager is not available at startup

- acra-core/src/main/java/org/acra/ACRA.java
- acra-core/src/main/java/org/acra/ErrorReporter.java
- acra-core/src/main/java/org/acra/prefs/SharedPreferencesFactory.java
- acra-core/src/main/java/org/acra/reporter/ErrorReporterImpl.java
- acra-core/src/main/java/org/acra/reporter/ErrorReporterStub.java
Alternative to #614 
We probably shouldn't throw exceptions as a crash reporting library.
> Warn from getErrorReporter instead of throwing exception

- acra-mail/src/main/java/org/acra/annotation/AcraMailSender.java
- acra-mail/src/main/java/org/acra/sender/EmailIntentSender.java
> Add subject & filename config in mail

- acra-core/src/main/java/org/acra/builder/ReportExecutor.java
- acra-core/src/main/java/org/acra/util/ApplicationStartupProcessor.java
> StrictMode compatibility

- annotationprocessor/src/main/java/org/acra/processor/creator/BuildMethodCreator.java
- annotationprocessor/src/main/java/org/acra/processor/creator/ClassCreator.java
- annotationprocessor/src/main/java/org/acra/processor/element/AnnotationField.java
- annotationprocessor/src/main/java/org/acra/processor/element/BuilderElement.java
- annotationprocessor/src/main/java/org/acra/processor/element/DelegateMethod.java
- annotationprocessor/src/main/java/org/acra/processor/element/ElementFactory.java
- annotationprocessor/src/main/java/org/acra/processor/element/TransformedField.java
- annotationprocessor/src/main/java/org/acra/processor/util/IsValidResourceVisitor.java
- annotationprocessor/src/main/java/org/acra/processor/util/ToCodeBlockVisitor.java
>  Fix default string values not set when annotation not present 

- acra-core/src/main/java/org/acra/builder/ReportExecutor.java
- acra-dialog/src/main/java/org/acra/dialog/BaseCrashReportDialog.java
> Handle some more strictmode violations

- acra-core/src/main/java/org/acra/ACRA.java
- acra-core/src/main/java/org/acra/builder/ReportExecutor.java
- acra-core/src/main/java/org/acra/collector/BaseReportFieldCollector.java
- acra-core/src/main/java/org/acra/data/CrashReportDataFactory.java
- acra-core/src/main/java/org/acra/legacy/ReportConverter.java
- acra-core/src/main/java/org/acra/reporter/ErrorReporterImpl.java
- acra-core/src/main/java/org/acra/util/PackageManagerWrapper.java
- acra-core/src/test/java/org/acra/ACRATest.java
- acra-notification/src/main/java/org/acra/receiver/NotificationBroadcastReceiver.java
- allow mulitple init calls
- do not catch errors (especially AssertionErrors)
@mikehardy you might be interested in the ACRATest class, as it serves as an example on how to test reports.
> Allow easier testing

- acra-core/src/main/java/org/acra/annotation/AcraCore.java
- acra-core/src/main/java/org/acra/reporter/ErrorReporterImpl.java
- acra-core/src/main/java/org/acra/startup/Report.java
- acra-core/src/main/java/org/acra/startup/StartupProcessor.java
- acra-core/src/main/java/org/acra/startup/StartupProcessorExecutor.java
- acra-core/src/main/java/org/acra/startup/UnapprovedStartupProcessor.java
- acra-core/src/main/java/org/acra/util/ApplicationStartupProcessor.java
- acra-limiter/src/main/java/org/acra/annotation/AcraLimiter.java
- acra-limiter/src/main/java/org/acra/config/LimiterData.java
- acra-limiter/src/main/java/org/acra/config/LimitingReportAdministrator.java
- acra-limiter/src/main/java/org/acra/startup/LimiterStartupProcessor.java
Closes #694 
@mikehardy you can call `new LimiterData().store(context)` to clear limiter data manually.
> StartupProcessor enhancements

- acra-advanced-scheduler/src/main/java/org/acra/scheduler/RestartingAdministrator.java
Fixes #742, and forces the system to execute the job (and therefore, to restart the app) "immediately"
> Fix "job without constraints" issue

- acra-dialog/src/main/java/org/acra/dialog/CrashReportDialog.java
> Resolve dialog padding from theme if present

- acra-dialog/src/main/java/org/acra/dialog/CrashReportDialog.kt
This allows complicated dynamic views in sub-classes
Related: https://github.com/ankidroid/Anki-Android/issues/7805#issuecomment-1076551146
> feat(dialog): open buildCustomView for override

- acra-core/src/main/java/org/acra/reporter/ErrorReporterImpl.kt
Underlying Java API documents it as potentially null
https://developer.android.com/reference/java/lang/Thread#getDefaultUncaughtExceptionHandler()
Null values are handled in ReportExecutor (the only consumer of this value that I know of?):
https://github.com/ACRA/acra/blob/042eddd1a649af3066ca5bf5c4573040533bcd32/acra-core/src/main/java/org/acra/builder/ReportExecutor.kt#L51
Fixes a crash in robolectric contexts where it actually is null
Test Plan: I made the correct package directory structure, copied the original version of the file in to AnkiDroid's codebase that way and ran it - reproduce the failure in our robolectric tests - ran this changed version and it worked
Also `./gradlew test` passed locally
> fix(core, reporter): default exception handler may be null

- acra-core/src/main/java/org/acra/startup/StartupProcessorExecutor.kt
I have been tracking down the reason why my app is constantly showing Toast interaction on App startup. From what I could understand, my app got to an state where there is a single unnaproved report instance. This report is processed by UnnaprovedStartupProcessor, and its "approve" property is set to true.
https://github.com/ACRA/acra/blob/f99e61da72ebfce78b5f80a6c6cc8f4672555670/acra-core/src/main/java/org/acra/startup/UnapprovedStartupProcessor.kt#L42
Since only its "approve" property is set to true, variable "send" remains as false during execution of StartupProcessorExecutor.processReports method. 
https://github.com/ACRA/acra/blob/f99e61da72ebfce78b5f80a6c6cc8f4672555670/acra-core/src/main/java/org/acra/startup/StartupProcessorExecutor.kt#L42-L57
The …
> Send most recent unnaproved report to avoid continuous interactions on App startup

- web/docs/Interactions.mdx
- web/docs/Setup.mdx
to match the Kotlin ones with the change from taking Strings as Resources to taking them as Text.
> Fix #1089 updated the Java documentation examples 

- web/docs/Interactions.mdx
When I tried copying the [notification interaction](https://www.acra.ch/docs/Interactions#notification) into my project, the `resChannelImportance` of the `NotificationConfigurationBuilder` could not be found.
It seems to be called `channelImportance` now?
[This](https://github.com/ACRA/acra/blob/0c2b36ceb873f75b7528cd76f2fefec3f0d5ac23/acra-notification/src/main/java/org/acra/config/NotificationConfiguration.kt#L136) should be the corresponding source code.
> fix(docs): fix notification channel importance usage

- web/docs/Custom-Extensions.mdx
In [Custom Extensions](https://www.acra.ch/docs/Custom-Extensions) page
> Fix typo : add "class" keyword

- web/docs/Senders.mdx
[acra-http throws a ReportSenderException if it fails to send the report](https://github.com/ACRA/acra/blob/master/acra-http/src/main/java/org/acra/sender/HttpSender.kt#L118), so I imagine it's a mechanism to allow for a later retry. ACRA's message is pretty clear: `org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again`.
I thought it would be nice to document it. It might need to be rephrased.
> Add a note about `ReportSenderException` 

- acra-core/proguard.cfg
This is in response to this warning and is simply the suggested change, with the intention that it is non-functional / results in the same keep behavior as before
> WARNING: /Users/mike/.gradle/caches/8.10.2/transforms/05e2bc486ed1e2d3388799eab04515e2/transformed/acra-core-5.11.4/proguard.txt:15:1-17:1: R8: The current version of R8 implicitly keeps the default constructor for Proguard configuration rules that have no member pattern. If the following rule should continue to keep the default constructor in the next major version of R8, then it must be augmented with the member pattern `{ void <init>(); }` to explicitly keep the default constructor: -keep interface org.acra.ErrorReporter
> fix: forward-port to R8 next major version
